# Generated by Django 4.0.4 on 2022-07-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_food_slug'),
        ('food_delivery_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.food'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.food'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
