# Generated by Django 4.0.4 on 2022-07-22 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_delivery_web', '0007_alter_order_order_id_alter_order_order_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='name',
            field=models.CharField(default='Abacha', max_length=30),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='order_status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='ordersID',
            field=models.CharField(default='nnbxcjhs2524jhsbv', max_length=30),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
