# Generated by Django 4.0.4 on 2022-06-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
    ]
