# Generated by Django 4.0.4 on 2022-07-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_rename_user_id_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
